'use client';
import { useEffect, useMemo, useState } from 'react';
import { acceptIntegrationReviewItem, fetchIntegrationReviewItems, fetchIntegrationReviewSummary, rejectIntegrationReviewItem, retryIntegrationReviewItem } from '../../lib/api';
import { fetchFinancialAccounts } from '../../lib/cashflowApi';

const effectLabels={cash_in:'Cash In',cash_out:'Cash Out',settlement:'Settlement',journal_only:'Journal Only',receivable:'Receivable',payable:'Payable',folio_charge:'Folio Charge',reference_only:'Reference'};
export default function ReviewInboxPage(){
 const [items,setItems]=useState([]),[summary,setSummary]=useState(null),[accounts,setAccounts]=useState([]),[selected,setSelected]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const [filters,setFilters]=useState({status:'ready_for_review',source_app:'',financial_effect:'',q:''});
 const load=async()=>{setError('');try{const [rows,sum,acc]=await Promise.all([fetchIntegrationReviewItems(filters),fetchIntegrationReviewSummary(),fetchFinancialAccounts()]);setItems(rows);setSummary(sum);setAccounts(acc);}catch(e){setError(e.message||'Failed to load Review Inbox.')}};
 useEffect(()=>{load();},[]);
 const counts=summary?.by_status||{};
 const accept=async(item)=>{setBusy(true);try{await acceptIntegrationReviewItem(item.id,{account_id:item.proposed_account_id||accounts[0]?.id||null,category:'Connected App'});setSelected(null);await load();}catch(e){setError(e.message||'Acceptance failed.')}finally{setBusy(false)}};
 const reject=async(item)=>{setBusy(true);try{await rejectIntegrationReviewItem(item.id,{reason:'Rejected during Accounting review'});setSelected(null);await load();}catch(e){setError(e.message||'Rejection failed.')}finally{setBusy(false)}};
 const retry=async(item)=>{setBusy(true);try{await retryIntegrationReviewItem(item.id,{});setSelected(null);await load();}catch(e){setError(e.message||'Retry failed.')}finally{setBusy(false)}};
 return <div className="stack">
  <section className="section page-header"><div><div className="eyebrow">Connected-app financial intake</div><h1>Review Inbox</h1><p className="muted">Accept each external financial event once. Cash items enter Cash & Treasury; non-cash items enter journals, payables, receivables, or linked balances.</p></div><button onClick={load}>Refresh</button></section>
  <section className="metric-grid"><div className="metric-card"><span>Needs review</span><strong>{summary?.needs_review||0}</strong></div><div className="metric-card"><span>Accepted</span><strong>{counts.accepted||0}</strong></div><div className="metric-card"><span>Failed validation</span><strong>{counts.validation_failed||0}</strong></div><div className="metric-card"><span>Rejected</span><strong>{counts.rejected||0}</strong></div></section>
  <section className="section"><div className="filter-bar"><select value={filters.status} onChange={e=>setFilters({...filters,status:e.target.value})}><option value="">All statuses</option><option value="ready_for_review">Needs review</option><option value="accepted">Accepted</option><option value="validation_failed">Failed validation</option><option value="rejected">Rejected</option></select><select value={filters.source_app} onChange={e=>setFilters({...filters,source_app:e.target.value})}><option value="">All apps</option><option value="pos">POS</option><option value="inventory">Inventory</option><option value="staff">Staff & Payroll</option><option value="beds24">Beds24</option><option value="operations">Operations</option></select><select value={filters.financial_effect} onChange={e=>setFilters({...filters,financial_effect:e.target.value})}><option value="">All effects</option>{Object.entries(effectLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><input placeholder="Search source ID or payload" value={filters.q} onChange={e=>setFilters({...filters,q:e.target.value})}/><button onClick={load}>Apply</button></div>{error&&<p className="error-text">{error}</p>}<div className="table-wrap"><table className="table"><thead><tr><th>Received</th><th>Source</th><th>Financial effect</th><th>Amount</th><th>Suggested result</th><th>Status</th><th></th></tr></thead><tbody>{items.map(item=><tr key={item.id}><td>{item.created_at?.slice(0,16).replace('T',' ')||'-'}</td><td><strong>{item.source_app}</strong><div className="small muted">{item.source_event_id}</div></td><td><span className="badge">{effectLabels[item.financial_effect]||item.financial_effect}</span></td><td>{Number(item.amount||0).toLocaleString(undefined,{style:'currency',currency:item.currency||'PHP'})}</td><td>{item.proposed_account_name||item.accepted_journal_entry_id&&'Journal'||item.accepted_receivable_id&&'Receivable'||item.accepted_payable_id&&'Payable'||'Review required'}</td><td><span className={`badge ${item.status==='accepted'?'success':item.status==='validation_failed'?'danger':''}`}>{item.status.replaceAll('_',' ')}</span></td><td><button className="secondary" onClick={()=>setSelected(item)}>Review</button></td></tr>)}{!items.length&&<tr><td colSpan="7" className="muted">No items match the filters.</td></tr>}</tbody></table></div></section>
  {selected&&<div className="drawer-backdrop" onClick={()=>setSelected(null)}><aside className="detail-drawer" onClick={e=>e.stopPropagation()}><div className="drawer-header"><div><div className="eyebrow">{selected.source_app}</div><h2>{selected.source_event_id}</h2></div><button className="icon-button" onClick={()=>setSelected(null)}>×</button></div><div className="drawer-content stack"><div className="card"><strong>{effectLabels[selected.financial_effect]||selected.financial_effect}</strong><div className="kpi">{Number(selected.amount||0).toLocaleString(undefined,{style:'currency',currency:selected.currency||'PHP'})}</div><p className="small muted">Entity: {selected.source_entity_type} {selected.source_entity_id||''}</p></div><div className="card"><strong>Acceptance result</strong><p className="small muted">Cash/settlement → one Money Transaction and reconciliation candidate. Journal-only → Journal. Receivable/Payable → open balance. Folio/reference effects retain their source link.</p>{['cash_in','cash_out','settlement'].includes(selected.financial_effect)&&<label>Financial account<select value={selected.proposed_account_id||''} onChange={e=>setSelected({...selected,proposed_account_id:Number(e.target.value)})}><option value="">Select account</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label>}</div><pre className="code-block">{JSON.stringify(selected.payload||{},null,2)}</pre><div className="row wrap">{selected.status==='ready_for_review'&&<><button disabled={busy} onClick={()=>accept(selected)}>Accept</button><button className="danger" disabled={busy} onClick={()=>reject(selected)}>Reject</button></>}{['validation_failed','rejected'].includes(selected.status)&&<button disabled={busy} onClick={()=>retry(selected)}>Retry</button>}</div></div></aside></div>}
 </div>;
}
