
'use client';
import { useEffect, useMemo, useState } from 'react';
import { createJournalEntry, fetchJournalEntries, fetchJournalEntryDetail, postJournalEntry, lockJournalEntry, reverseJournalEntry } from '../../lib/api';
function newLine(){return {account_code:'',account_name:'',debit:'0',credit:'0',memo:''};}
export default function JournalsPage(){
 const [rows,setRows]=useState([]); const [selected,setSelected]=useState(null); const [error,setError]=useState('');
 const [entry,setEntry]=useState({entry_date:'',reference_no:'',description:'',source_module:'finance',status:'draft'}); const [lines,setLines]=useState([newLine(),newLine()]);
 async function load(){setRows(await fetchJournalEntries());}
 useEffect(()=>{load().catch(e=>setError(e.message));},[]);
 const totals=useMemo(()=>{const debit=lines.reduce((s,l)=>s+Number(l.debit||0),0),credit=lines.reduce((s,l)=>s+Number(l.credit||0),0);return {debit,credit,balanced:Math.round(debit*100)===Math.round(credit*100)};},[lines]);
 async function submit(e){e.preventDefault();setError('');try{await createJournalEntry({...entry,lines:lines.filter(l=>l.account_code||l.account_name||Number(l.debit)||Number(l.credit)).map(l=>({...l,debit:Number(l.debit||0),credit:Number(l.credit||0)}))});setEntry({entry_date:'',reference_no:'',description:'',source_module:'finance',status:'draft'});setLines([newLine(),newLine()]);await load();}catch(e){setError(e.message);}}
 async function open(id){setSelected(await fetchJournalEntryDetail(id));}
 async function act(fn,id){await fn(id);setSelected(await fetchJournalEntryDetail(id));await load();}
 return <div className="stack"><section className="section"><h1>Journals</h1><p className="muted">Balanced entries, posting, journal locks, reversals, and audit history.</p>{error&&<p className="error-text">{error}</p>}</section>
 <div className="grid"><section className="section"><h2>Create Entry</h2><form onSubmit={submit}><div className="form-grid"><label>Date<input type="date" value={entry.entry_date} onChange={e=>setEntry(f=>({...f,entry_date:e.target.value}))}/></label><label>Reference<input value={entry.reference_no} onChange={e=>setEntry(f=>({...f,reference_no:e.target.value}))}/></label><label>Status<select value={entry.status} onChange={e=>setEntry(f=>({...f,status:e.target.value}))}><option value="draft">Draft</option><option value="posted">Post immediately</option></select></label></div><label>Description<textarea value={entry.description} onChange={e=>setEntry(f=>({...f,description:e.target.value}))}/></label><div className="row" style={{justifyContent:'space-between'}}><h3>Lines</h3><span className={totals.balanced?'badge':'error-text'}>Debit {totals.debit.toLocaleString()} / Credit {totals.credit.toLocaleString()}</span></div>{lines.map((line,i)=><div key={i} className="form-grid"><label>Code<input value={line.account_code} onChange={e=>setLines(x=>x.map((l,j)=>j===i?{...l,account_code:e.target.value}:l))}/></label><label>Name<input value={line.account_name} onChange={e=>setLines(x=>x.map((l,j)=>j===i?{...l,account_name:e.target.value}:l))}/></label><label>Debit<input type="number" step="0.01" value={line.debit} onChange={e=>setLines(x=>x.map((l,j)=>j===i?{...l,debit:e.target.value}:l))}/></label><label>Credit<input type="number" step="0.01" value={line.credit} onChange={e=>setLines(x=>x.map((l,j)=>j===i?{...l,credit:e.target.value}:l))}/></label></div>)}<div className="row"><button type="button" className="secondary" onClick={()=>setLines(x=>[...x,newLine()])}>Add line</button><button disabled={!totals.balanced}>Save entry</button></div></form></section>
 <section className="section"><h2>Entry Register</h2><table className="table"><thead><tr><th>Date</th><th>Reference</th><th>Status</th><th>Source</th><th>Control</th></tr></thead><tbody>{rows.map(r=><tr key={r.id} onClick={()=>open(r.id)} style={{cursor:'pointer'}}><td>{r.entry_date||'-'}</td><td>{r.reference_no||`JE-${r.id}`}</td><td><span className="badge">{r.is_reversed?'reversed':r.status}</span></td><td>{r.source_module||'-'}</td><td>{r.locked?'Locked':'Open'}</td></tr>)}</tbody></table></section></div>
 {selected&&<section className="section"><div className="row" style={{justifyContent:'space-between'}}><div><h2>{selected.entry.reference_no||`JE-${selected.entry.id}`}</h2><p className="muted">{selected.entry.description}</p></div><button className="secondary" onClick={()=>setSelected(null)}>Close</button></div><div className="row wrap"><span className="badge">{selected.entry.status}</span>{selected.entry.locked&&<span className="badge">Locked by {selected.entry.locked_by||'user'}</span>}{selected.entry.is_reversed&&<span className="badge">Reversed</span>}</div><table className="table"><thead><tr><th>Code</th><th>Account</th><th>Debit</th><th>Credit</th></tr></thead><tbody>{selected.entry.lines.map(l=><tr key={l.id}><td>{l.account_code}</td><td>{l.account_name}</td><td>{Number(l.debit||0).toLocaleString()}</td><td>{Number(l.credit||0).toLocaleString()}</td></tr>)}</tbody></table><div className="row wrap">{selected.entry.status==='draft'&&<button onClick={()=>act(postJournalEntry,selected.entry.id)}>Post</button>}{selected.entry.status==='posted'&&!selected.entry.locked&&!selected.entry.is_reversed&&<button onClick={()=>act(lockJournalEntry,selected.entry.id)}>Lock journal</button>}{selected.entry.status==='posted'&&!selected.entry.is_reversed&&<button className="secondary" onClick={()=>act(reverseJournalEntry,selected.entry.id)}>Reverse</button>}</div><h3 style={{marginTop:18}}>Audit history</h3><div className="stack">{selected.audit.map(a=><div className="card" key={a.id}><strong>{a.action}</strong><div className="small muted">{a.username||'system'} · {a.created_at}</div></div>)}{!selected.audit.length&&<p className="muted">No audit events yet.</p>}</div></section>}</div>;
}
