// Access rules are shared with RouteGuard in lib/routeAccess.js.
export const navigationGroups = [
  {
    id: 'overview',
    label: 'Overview',
    description: 'Daily priorities and review queues',
    icon: 'dashboard',
    items: [
      { href: '/dashboard', label: 'Dashboard', icon: 'dashboard' },
      { href: '/start-of-day', label: 'Start of Day', icon: 'sun' },
      { href: '/review-inbox', label: 'Review Inbox', icon: 'review' },
      { href: '/approvals', label: 'Approvals', icon: 'shield' },
    ],
  },
  {
    id: 'money',
    label: 'Money',
    description: 'Cash, bank, transfers, and reconciliation',
    icon: 'wallet',
    items: [
      { href: '/cashflow', label: 'Cash Overview', icon: 'wallet' },
      { href: '/cashflow/ledger', label: 'Cash Ledger', icon: 'journal' },
      { href: '/cashflow/money-in', label: 'Money In', icon: 'receivable' },
      { href: '/cashflow/money-out', label: 'Money Out', icon: 'payable' },
      { href: '/cashflow/transfers', label: 'Transfers', icon: 'mapping' },
      { href: '/cashflow/daily-cash', label: 'Daily Close & Reconciliation', icon: 'receipt' },
      { href: '/cashflow/settings', label: 'Cash Settings', icon: 'settings' },
    ],
  },
  {
    id: 'sales',
    label: 'Sales & Receivables',
    description: 'Guest balances, collections, and channel payouts',
    icon: 'receivable',
    items: [
      { href: '/cashflow/receivables', label: 'Receivables', icon: 'receivable' },
      { href: '/room-folios', label: 'Guest Folios', icon: 'receipt' },
      { href: '/channel-payouts', label: 'Channel Payouts', icon: 'payout' },
      { href: '/guests', label: 'Guests', icon: 'users' },
      { href: '/bookings', label: 'Bookings', icon: 'calendar' },
      { href: '/events', label: 'Events', icon: 'event' },
    ],
  },
  {
    id: 'purchases',
    label: 'Purchases & Payables',
    description: 'Bills, suppliers, purchasing, and receiving',
    icon: 'payable',
    items: [
      { href: '/cashflow/payables', label: 'Payables', icon: 'payable' },
      { href: '/suppliers', label: 'Suppliers', icon: 'users' },
      { href: '/purchase-requests', label: 'Purchase Requests', icon: 'file' },
      { href: '/purchase-orders', label: 'Purchase Orders', icon: 'receipt' },
      { href: '/receiving', label: 'Receiving', icon: 'database' },
    ],
  },
  {
    id: 'accounting',
    label: 'Accounting',
    description: 'Ledgers, reporting, tax, and close',
    icon: 'journal',
    items: [
      { href: '/journals', label: 'Journal Entries', icon: 'journal' },
      { href: '/chart-of-accounts', label: 'Chart of Accounts', icon: 'accounts' },
      { href: '/account-mapping', label: 'Posting Rules', icon: 'mapping' },
      { href: '/bir', label: 'Tax & Period Close', icon: 'file' },
      { href: '/assets', label: 'Fixed Assets', icon: 'asset' },
      { href: '/reports', label: 'Reports', icon: 'chart' },
      { href: '/attachments', label: 'Files & Evidence', icon: 'paperclip' },
    ],
  },
  {
    id: 'integrations',
    label: 'Operations Integration',
    description: 'Hotel, POS, inventory, and payroll connections',
    icon: 'link',
    items: [
      { href: '/integrations/beds24', label: 'Beds24', icon: 'link' },
      { href: '/integrations/payroll', label: 'Payroll Integration', icon: 'users' },
      { href: '/restaurant-ops', label: 'Restaurant / POS', icon: 'app' },
      { href: '/inventory-items', label: 'Inventory', icon: 'database' },
      { href: '/inventory-reconciliation', label: 'Inventory Reconciliation', icon: 'review' },
    ],
  },
  {
    id: 'administration',
    label: 'Administration',
    description: 'Access, setup, master data, and system controls',
    icon: 'settings',
    items: [
      { href: '/room-types', label: 'Rooms & Rates', icon: 'hotel' },
      { href: '/master-data', label: 'Master Data', icon: 'database' },
      { href: '/users', label: 'Users', icon: 'users' },
      { href: '/roles-permissions', label: 'Roles & Permissions', icon: 'shield' },
      { href: '/taxonomy-admin', label: 'Taxonomies', icon: 'mapping' },
      { href: '/system-settings', label: 'System Settings', icon: 'settings' },
      { href: '/staff-guide', label: 'Staff Guide', icon: 'book' },
    ],
  },
];

export const legacyWorkspaceLinks = [
  { href: '/restaurant-ops', label: 'Restaurant Operations', app: 'POS Cloud' },
  { href: '/inventory-items', label: 'Inventory & Purchasing', app: 'Inventory & Procurement' },
  { href: '/payroll-periods', label: 'People & Payroll', app: 'Staff & Payroll' },
];