export const navigationGroups = [
  {
    id: 'overview',
    label: 'Overview',
    description: 'Daily priorities and review queues',
    icon: 'dashboard',
    items: [
      { href: '/dashboard', label: 'Dashboard', icon: 'dashboard', permissionsAny: ['dashboard.view'] },
      { href: '/start-of-day', label: 'Start of Day', icon: 'sun', permissionsAny: ['dashboard.view', 'cashflow.view'] },
      { href: '/review-inbox', label: 'Review Inbox', icon: 'review', permissionsAny: ['approvals.view', 'integrations.view'] },
      { href: '/approvals', label: 'Approvals', icon: 'shield', permissionsAny: ['approvals.view'] },
    ],
  },
  {
    id: 'money',
    label: 'Money',
    description: 'Cash, bank, transfers, and reconciliation',
    icon: 'wallet',
    items: [
      { href: '/cashflow', label: 'Cash Overview', icon: 'wallet', permissionsAny: ['cashflow.view'] },
      { href: '/cashflow/money-in', label: 'Money In', icon: 'receivable', permissionsAny: ['cashflow.view'] },
      { href: '/cashflow/money-out', label: 'Money Out', icon: 'payable', permissionsAny: ['cashflow.view'] },
      { href: '/cashflow/transfers', label: 'Transfers', icon: 'mapping', permissionsAny: ['cashflow.view'] },
      { href: '/cashflow/daily-cash', label: 'Daily Cash', icon: 'receipt', permissionsAny: ['cashflow.view'] },
      { href: '/cashflow/reconciliation', label: 'Reconciliation', icon: 'review', permissionsAny: ['cashflow.view'] },
    ],
  },
  {
    id: 'sales',
    label: 'Sales & Receivables',
    description: 'Guest balances, collections, and channel payouts',
    icon: 'receivable',
    items: [
      { href: '/cashflow/receivables', label: 'Receivables', icon: 'receivable', permissionsAny: ['cashflow.view'] },
      { href: '/room-folios', label: 'Guest Folios', icon: 'receipt', permissionsAny: ['folios.view'] },
      { href: '/channel-payouts', label: 'Channel Payouts', icon: 'payout', permissionsAny: ['bookings.view', 'cashflow.view', 'reports.view'] },
      { href: '/guests', label: 'Guests', icon: 'users', permissionsAny: ['guests.view'] },
      { href: '/bookings', label: 'Bookings', icon: 'calendar', permissionsAny: ['bookings.view'] },
      { href: '/events', label: 'Events', icon: 'event', permissionsAny: ['bookings.view', 'cashflow.view'] },
    ],
  },
  {
    id: 'purchases',
    label: 'Purchases & Payables',
    description: 'Bills, suppliers, purchasing, and receiving',
    icon: 'payable',
    items: [
      { href: '/cashflow/payables', label: 'Payables', icon: 'payable', permissionsAny: ['cashflow.view'] },
      { href: '/suppliers', label: 'Suppliers', icon: 'users', permissionsAny: ['cashflow.view', 'master_data.manage'] },
      { href: '/purchase-requests', label: 'Purchase Requests', icon: 'file', permissionsAny: ['cashflow.view', 'approvals.view'] },
      { href: '/purchase-orders', label: 'Purchase Orders', icon: 'receipt', permissionsAny: ['cashflow.view', 'approvals.view'] },
      { href: '/receiving', label: 'Receiving', icon: 'database', permissionsAny: ['cashflow.view'] },
    ],
  },
  {
    id: 'accounting',
    label: 'Accounting',
    description: 'Ledgers, reporting, tax, and close',
    icon: 'journal',
    items: [
      { href: '/journals', label: 'Journal Entries', icon: 'journal', permissionsAny: ['journals.view'] },
      { href: '/chart-of-accounts', label: 'Chart of Accounts', icon: 'accounts', permissionsAny: ['chart_of_accounts.manage'] },
      { href: '/account-mapping', label: 'Posting Rules', icon: 'mapping', permissionsAny: ['account_mapping.manage'] },
      { href: '/bir', label: 'Tax & Period Close', icon: 'file', permissionsAny: ['bir.view'] },
      { href: '/assets', label: 'Fixed Assets', icon: 'asset', permissionsAny: ['assets.view'] },
      { href: '/reports', label: 'Reports', icon: 'chart', permissionsAny: ['reports.view'] },
      { href: '/attachments', label: 'Files & Evidence', icon: 'paperclip', permissionsAny: ['reports.view', 'cashflow.view', 'bookings.view', 'assets.view', 'bir.view'] },
    ],
  },
  {
    id: 'integrations',
    label: 'Operations Integration',
    description: 'Hotel, POS, inventory, and payroll connections',
    icon: 'link',
    items: [
      { href: '/integrations/beds24', label: 'Beds24', icon: 'link', permissionsAny: ['integrations.view'] },
      { href: '/integrations/payroll', label: 'Payroll Integration', icon: 'users', permissionsAny: ['integrations.view', 'reports.view'] },
      { href: '/restaurant-ops', label: 'Restaurant / POS', icon: 'app', permissionsAny: ['integrations.view', 'cashflow.view'] },
      { href: '/inventory-items', label: 'Inventory', icon: 'database', permissionsAny: ['integrations.view', 'cashflow.view'] },
      { href: '/inventory-reconciliation', label: 'Inventory Reconciliation', icon: 'review', permissionsAny: ['integrations.view', 'cashflow.view'] },
    ],
  },
  {
    id: 'administration',
    label: 'Administration',
    description: 'Access, setup, master data, and system controls',
    icon: 'settings',
    items: [
      { href: '/room-types', label: 'Rooms & Rates', icon: 'hotel', permissionsAny: ['room_setup.view'] },
      { href: '/master-data', label: 'Master Data', icon: 'database', permissionsAny: ['master_data.manage', 'taxonomy.manage'] },
      { href: '/roles-permissions', label: 'Users & Access', icon: 'shield', permissionsAny: ['roles.manage', 'users.manage'] },
      { href: '/system-settings', label: 'System Settings', icon: 'settings', permissionsAny: ['system_settings.manage', 'integrations.manage'] },
      { href: '/staff-guide', label: 'Staff Guide', icon: 'book', permissionsAny: [] },
    ],
  },
];

export const legacyWorkspaceLinks = [
  { href: '/restaurant-ops', label: 'Restaurant Operations', app: 'POS Cloud' },
  { href: '/inventory-items', label: 'Inventory & Purchasing', app: 'Inventory & Procurement' },
  { href: '/payroll-periods', label: 'People & Payroll', app: 'Staff & Payroll' },
];